<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="11.7010" tests="2" failures="1">
  <testsuite name="Root Suite" timestamp="2022-05-10T17:38:01" tests="0" file="cypress/integration/addMessage.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="add message" timestamp="2022-05-10T17:38:01" tests="2" time="11.6560" failures="1">
    <testcase name="add message login" time="7.0590" classname="login">
    </testcase>
    <testcase name="add message create message" time="0.0000" classname="create message">
      <failure message="Timed out retrying after 4000ms: Expected to find content: &apos;Message&apos; within the selector: &apos;a&apos; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Message' within the selector: 'a' but never did.
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\support\index.js:110:8)]]></failure>
    </testcase>
  </testsuite>
</testsuites>